version: "3"
services:
  collaborator_app: 
    container_name: collaborator_app
    build: .
    ports:
      - "3000:3000"
  collaborator_nginx: 
    container_name: collaborator_nginx
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ".:/var/www/html/collaborator_service"
      - "./nginx/conf.d:/etc/nginx/conf.d/"
      
